### ISSUE TITLE
ATTRIBUTE @unit description

### ISSUE THREAD

**Issue by mcdittmar** [ivoa-std/ModelInstanceInVot#127] opened 2022-07-22 21:32 UTC
I know we had a long discussion about this back some time ago.. but the description of this element does not match my recollection.  Maybe I've forgotten or there was further discussion that I missed.

Section 4.8: ATTRIBUTE
  * unit: ATTRIBUTE unit. This is the unit in which the native value must be converted to be compliant with the model. This attribute is always optional.

I recall that this is primarily for the 'LITERAL' case to enable providers to give a \@value and \@unit.
I do recall some discussion about how this might interact if the referenced PARAM has a unit also.. which one takes precedence.
But I don't recall a discussion that if the PARAM|FIELD unit were different from the ATTRIBUTE unit, that means to convert the native value to the specified units.

Maybe someone can catch me up?
Either way, I think the usage as "LITERAL" should be in the description as well, I think/hope that is the most common usage.

Mark

**Comment by lmichel** [comment] 2022-07-25 12:16
I recall we discussed this topic without clear conclusion.
The problem is the unit can apply to ref or value and ref can inherit the FIELD unit.
The matrix below gives all cases among 2 have no answer yet. 

| nb | @value | @ref | @unit == FIELD unit | @unit != FIELD unit | client behavior |
| --- | -----------| ------- | --------------------------- | --------------------------- | -------------------  |
| 1   | yes       | yes    | yes                            | no                             | take ATTRIBUTE unit |
| 2   | yes | yes  | no | yes | ??
| 3   | yes | no |  yes (no FIELD) | yes (no FIELD)| take ATTRIBUTE unit |
| 4   | no  | yes | yes  | no | take FIELD unit |
| 5   | no | yes | no  | yes | ??? |

The spec must tell what to do for 2 and 5

**Comment by mcdittmar** [comment] 2022-07-25 15:56
Ah.. OK.  We certainly don't want to open that up again :)

IMO, the primary purpose of the unit in ATTRIBUTE is to provide units in the "as LITERAL" case.  The current text implies/states that the primary purpose is to impose a conversion directive.

Options for what to do if the ATTRIBUTE has both \@units  and \@ref

1. referenced PARAM/FIELD has no \@unit;  the annotation is providing missing metadata
2. referenced PARAM/FIELD has \@unit == Attribute \@unit;  No problem; just duplicated information
3. referenced PARAM/FIELD has \@unit != Attribute \@unit  (case 2&5 in your table above).  

case 3. could be considered either:
  1) an Error.. require Attribute.unit == Field.unit if present in both.
  2) an override of the Field.unit.. perhaps the Field has a unit expressed in an invalid syntax (as per the model) or is incorrect e.g. Visier's "h:m:s" for sexagesimal. This does NOT require conversion of the native value, but provides a model-valid unit expression for the value.
  3) an override of the Field unit.. as a directive to convert the referenced value to this unit.  This is what is currently expressed in the document and I think this has a big impact.  It basically means that code MUST implement unit conversion capabilities to interpret the annotation syntax.  I don't think we want that.
  4) outside the scope of the syntax document to define how to resolve inconsistent units in Attribute vs referenced Field.

**Comment by lmichel** [comment] 2022-07-25 17:09
I agree with 2 (and 4),

To summarize  we have 2 cases
- `@unit`  applied to `@value`
  - `@unit` is the unit in which `@value` is expressed
  - if there is no `@unit` the syntax is valid although a possible lack of meta data.

- `@unit`  applied to  a resolved `@ref`
  - must be consistent with the FIELD unit (equals or VO formatted)
  - if not the syntax is valid but the unit inconsistency must be tackled by the client.

In any case, the `@unit`  must conform to VOUnit.

We need a small paragraph to detail this point.

**Comment by lmichel** [comment] 2022-09-06 08:02
Fixed by #134

**Closed** 2022-09-06 08:15 UTC
